service: my-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1


functions:
  hello:
    handler: handler.hello
    layers:
      - { Ref: MyServiceLambdaLayer }

layers:
  MyService:
    path: layer
    description: my service layer
    compatibleRuntimes:
      - nodejs12.x
